theme: minima
# title: "CocoNotes"
# description: "A text-based notes and todo lists app with auto-save, syntax highlighting and keyboard shortcuts"
url: "http://andriykrefer.github.io/coconotes"
github_username:  andriykrefer
google_analytics: UA-104226386-1
